name: AllMinecraft
version: '${project.version}'
main: de.rollocraft.allminecraft.Main
api-version: '1.20'
commands:
  skipitem:
    description: Skips the current item!
    usage: /skipitem
    permission: allminecraft.command.skipitem
  backpack:
    description: Opens the backpack!
    usage: /backpack
    aliases: bp
  timer:
    permission: allminecraft.command.timer
  position:
    aliases: pos
  mobviewer:
    aliases: mv
  itemviewer:
    aliases: iv
  save-allminecraft:
    permission: allminecraft.command.save-allminecraft
    aliases: sam
